### ISSUE TITLE
sonar

### ISSUE THREAD

**Issue by guilloca** [cs361fall2018/project-team-33#45]
So the issue with sonar is when you run it, it says it can't complete the action when you try to execute the pulse on a square. So somewhere in the process of making the pulse there is an issue. It sets everything up fine, makes sure you have the right amount sunk, creates a second board, but just doesn't finish the pulse
All the code is there, theres just a bug somewhere that I can't find. It's pretty hard to find it to, because intellij isn't the best for debugging

**Comment by youngerj** [comment]
Also need to create a test case for sonar pulse
